/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamTasksRouteImport } from './routes/team-tasks'
import { Route as StakeholdersRouteImport } from './routes/stakeholders'
import { Route as SprintBoardRouteImport } from './routes/sprint-board'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as ProgramOverviewRouteImport } from './routes/program-overview'
import { Route as LifecycleRouteImport } from './routes/lifecycle'
import { Route as DependenciesRouteImport } from './routes/dependencies'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'

const TeamTasksRoute = TeamTasksRouteImport.update({
  id: '/team-tasks',
  path: '/team-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholdersRoute = StakeholdersRouteImport.update({
  id: '/stakeholders',
  path: '/stakeholders',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintBoardRoute = SprintBoardRouteImport.update({
  id: '/sprint-board',
  path: '/sprint-board',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramOverviewRoute = ProgramOverviewRouteImport.update({
  id: '/program-overview',
  path: '/program-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleRoute = LifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const DependenciesRoute = DependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/artifacts': typeof ArtifactsRoute
  '/dependencies': typeof DependenciesRoute
  '/lifecycle': typeof LifecycleRoute
  '/program-overview': typeof ProgramOverviewRoute
  '/risks': typeof RisksRoute
  '/sprint-board': typeof SprintBoardRoute
  '/stakeholders': typeof StakeholdersRoute
  '/team-tasks': typeof TeamTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/artifacts': typeof ArtifactsRoute
  '/dependencies': typeof DependenciesRoute
  '/lifecycle': typeof LifecycleRoute
  '/program-overview': typeof ProgramOverviewRoute
  '/risks': typeof RisksRoute
  '/sprint-board': typeof SprintBoardRoute
  '/stakeholders': typeof StakeholdersRoute
  '/team-tasks': typeof TeamTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/artifacts': typeof ArtifactsRoute
  '/dependencies': typeof DependenciesRoute
  '/lifecycle': typeof LifecycleRoute
  '/program-overview': typeof ProgramOverviewRoute
  '/risks': typeof RisksRoute
  '/sprint-board': typeof SprintBoardRoute
  '/stakeholders': typeof StakeholdersRoute
  '/team-tasks': typeof TeamTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/artifacts'
    | '/dependencies'
    | '/lifecycle'
    | '/program-overview'
    | '/risks'
    | '/sprint-board'
    | '/stakeholders'
    | '/team-tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/artifacts'
    | '/dependencies'
    | '/lifecycle'
    | '/program-overview'
    | '/risks'
    | '/sprint-board'
    | '/stakeholders'
    | '/team-tasks'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/artifacts'
    | '/dependencies'
    | '/lifecycle'
    | '/program-overview'
    | '/risks'
    | '/sprint-board'
    | '/stakeholders'
    | '/team-tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ArtifactsRoute: typeof ArtifactsRoute
  DependenciesRoute: typeof DependenciesRoute
  LifecycleRoute: typeof LifecycleRoute
  ProgramOverviewRoute: typeof ProgramOverviewRoute
  RisksRoute: typeof RisksRoute
  SprintBoardRoute: typeof SprintBoardRoute
  StakeholdersRoute: typeof StakeholdersRoute
  TeamTasksRoute: typeof TeamTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team-tasks': {
      id: '/team-tasks'
      path: '/team-tasks'
      fullPath: '/team-tasks'
      preLoaderRoute: typeof TeamTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholders': {
      id: '/stakeholders'
      path: '/stakeholders'
      fullPath: '/stakeholders'
      preLoaderRoute: typeof StakeholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprint-board': {
      id: '/sprint-board'
      path: '/sprint-board'
      fullPath: '/sprint-board'
      preLoaderRoute: typeof SprintBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-overview': {
      id: '/program-overview'
      path: '/program-overview'
      fullPath: '/program-overview'
      preLoaderRoute: typeof ProgramOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle': {
      id: '/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof LifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependencies': {
      id: '/dependencies'
      path: '/dependencies'
      fullPath: '/dependencies'
      preLoaderRoute: typeof DependenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ArtifactsRoute: ArtifactsRoute,
  DependenciesRoute: DependenciesRoute,
  LifecycleRoute: LifecycleRoute,
  ProgramOverviewRoute: ProgramOverviewRoute,
  RisksRoute: RisksRoute,
  SprintBoardRoute: SprintBoardRoute,
  StakeholdersRoute: StakeholdersRoute,
  TeamTasksRoute: TeamTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
