/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProgramIdRouteRouteImport } from './routes/p/$programId/route'
import { Route as PProgramIdIndexRouteImport } from './routes/p/$programId/index'
import { Route as PProgramIdTeamTasksRouteImport } from './routes/p/$programId/team-tasks'
import { Route as PProgramIdStakeholdersRouteImport } from './routes/p/$programId/stakeholders'
import { Route as PProgramIdSprintBoardRouteImport } from './routes/p/$programId/sprint-board'
import { Route as PProgramIdRisksRouteImport } from './routes/p/$programId/risks'
import { Route as PProgramIdProgramOverviewRouteImport } from './routes/p/$programId/program-overview'
import { Route as PProgramIdLifecycleRouteImport } from './routes/p/$programId/lifecycle'
import { Route as PProgramIdFollowUpsRouteImport } from './routes/p/$programId/follow-ups'
import { Route as PProgramIdDependenciesRouteImport } from './routes/p/$programId/dependencies'
import { Route as PProgramIdCustomerHealthRouteImport } from './routes/p/$programId/customer-health'
import { Route as PProgramIdArtifactsRouteImport } from './routes/p/$programId/artifacts'
import { Route as PProgramIdActivityRouteImport } from './routes/p/$programId/activity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProgramIdRouteRoute = PProgramIdRouteRouteImport.update({
  id: '/p/$programId',
  path: '/p/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProgramIdIndexRoute = PProgramIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProgramIdRouteRoute,
} as any)
const PProgramIdTeamTasksRoute = PProgramIdTeamTasksRouteImport.update({
  id: '/team-tasks',
  path: '/team-tasks',
  getParentRoute: () => PProgramIdRouteRoute,
} as any)
const PProgramIdStakeholdersRoute = PProgramIdStakeholdersRouteImport.update({
  id: '/stakeholders',
  path: '/stakeholders',
  getParentRoute: () => PProgramIdRouteRoute,
} as any)
const PProgramIdSprintBoardRoute = PProgramIdSprintBoardRouteImport.update({
  id: '/sprint-board',
  path: '/sprint-board',
  getParentRoute: () => PProgramIdRouteRoute,
} as any)
const PProgramIdRisksRoute = PProgramIdRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => PProgramIdRouteRoute,
} as any)
const PProgramIdProgramOverviewRoute =
  PProgramIdProgramOverviewRouteImport.update({
    id: '/program-overview',
    path: '/program-overview',
    getParentRoute: () => PProgramIdRouteRoute,
  } as any)
const PProgramIdLifecycleRoute = PProgramIdLifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => PProgramIdRouteRoute,
} as any)
const PProgramIdFollowUpsRoute = PProgramIdFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => PProgramIdRouteRoute,
} as any)
const PProgramIdDependenciesRoute = PProgramIdDependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => PProgramIdRouteRoute,
} as any)
const PProgramIdCustomerHealthRoute =
  PProgramIdCustomerHealthRouteImport.update({
    id: '/customer-health',
    path: '/customer-health',
    getParentRoute: () => PProgramIdRouteRoute,
  } as any)
const PProgramIdArtifactsRoute = PProgramIdArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => PProgramIdRouteRoute,
} as any)
const PProgramIdActivityRoute = PProgramIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PProgramIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$programId': typeof PProgramIdRouteRouteWithChildren
  '/p/$programId/activity': typeof PProgramIdActivityRoute
  '/p/$programId/artifacts': typeof PProgramIdArtifactsRoute
  '/p/$programId/customer-health': typeof PProgramIdCustomerHealthRoute
  '/p/$programId/dependencies': typeof PProgramIdDependenciesRoute
  '/p/$programId/follow-ups': typeof PProgramIdFollowUpsRoute
  '/p/$programId/lifecycle': typeof PProgramIdLifecycleRoute
  '/p/$programId/program-overview': typeof PProgramIdProgramOverviewRoute
  '/p/$programId/risks': typeof PProgramIdRisksRoute
  '/p/$programId/sprint-board': typeof PProgramIdSprintBoardRoute
  '/p/$programId/stakeholders': typeof PProgramIdStakeholdersRoute
  '/p/$programId/team-tasks': typeof PProgramIdTeamTasksRoute
  '/p/$programId/': typeof PProgramIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$programId/activity': typeof PProgramIdActivityRoute
  '/p/$programId/artifacts': typeof PProgramIdArtifactsRoute
  '/p/$programId/customer-health': typeof PProgramIdCustomerHealthRoute
  '/p/$programId/dependencies': typeof PProgramIdDependenciesRoute
  '/p/$programId/follow-ups': typeof PProgramIdFollowUpsRoute
  '/p/$programId/lifecycle': typeof PProgramIdLifecycleRoute
  '/p/$programId/program-overview': typeof PProgramIdProgramOverviewRoute
  '/p/$programId/risks': typeof PProgramIdRisksRoute
  '/p/$programId/sprint-board': typeof PProgramIdSprintBoardRoute
  '/p/$programId/stakeholders': typeof PProgramIdStakeholdersRoute
  '/p/$programId/team-tasks': typeof PProgramIdTeamTasksRoute
  '/p/$programId': typeof PProgramIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$programId': typeof PProgramIdRouteRouteWithChildren
  '/p/$programId/activity': typeof PProgramIdActivityRoute
  '/p/$programId/artifacts': typeof PProgramIdArtifactsRoute
  '/p/$programId/customer-health': typeof PProgramIdCustomerHealthRoute
  '/p/$programId/dependencies': typeof PProgramIdDependenciesRoute
  '/p/$programId/follow-ups': typeof PProgramIdFollowUpsRoute
  '/p/$programId/lifecycle': typeof PProgramIdLifecycleRoute
  '/p/$programId/program-overview': typeof PProgramIdProgramOverviewRoute
  '/p/$programId/risks': typeof PProgramIdRisksRoute
  '/p/$programId/sprint-board': typeof PProgramIdSprintBoardRoute
  '/p/$programId/stakeholders': typeof PProgramIdStakeholdersRoute
  '/p/$programId/team-tasks': typeof PProgramIdTeamTasksRoute
  '/p/$programId/': typeof PProgramIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$programId'
    | '/p/$programId/activity'
    | '/p/$programId/artifacts'
    | '/p/$programId/customer-health'
    | '/p/$programId/dependencies'
    | '/p/$programId/follow-ups'
    | '/p/$programId/lifecycle'
    | '/p/$programId/program-overview'
    | '/p/$programId/risks'
    | '/p/$programId/sprint-board'
    | '/p/$programId/stakeholders'
    | '/p/$programId/team-tasks'
    | '/p/$programId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$programId/activity'
    | '/p/$programId/artifacts'
    | '/p/$programId/customer-health'
    | '/p/$programId/dependencies'
    | '/p/$programId/follow-ups'
    | '/p/$programId/lifecycle'
    | '/p/$programId/program-overview'
    | '/p/$programId/risks'
    | '/p/$programId/sprint-board'
    | '/p/$programId/stakeholders'
    | '/p/$programId/team-tasks'
    | '/p/$programId'
  id:
    | '__root__'
    | '/'
    | '/p/$programId'
    | '/p/$programId/activity'
    | '/p/$programId/artifacts'
    | '/p/$programId/customer-health'
    | '/p/$programId/dependencies'
    | '/p/$programId/follow-ups'
    | '/p/$programId/lifecycle'
    | '/p/$programId/program-overview'
    | '/p/$programId/risks'
    | '/p/$programId/sprint-board'
    | '/p/$programId/stakeholders'
    | '/p/$programId/team-tasks'
    | '/p/$programId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PProgramIdRouteRoute: typeof PProgramIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$programId': {
      id: '/p/$programId'
      path: '/p/$programId'
      fullPath: '/p/$programId'
      preLoaderRoute: typeof PProgramIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$programId/': {
      id: '/p/$programId/'
      path: '/'
      fullPath: '/p/$programId/'
      preLoaderRoute: typeof PProgramIdIndexRouteImport
      parentRoute: typeof PProgramIdRouteRoute
    }
    '/p/$programId/team-tasks': {
      id: '/p/$programId/team-tasks'
      path: '/team-tasks'
      fullPath: '/p/$programId/team-tasks'
      preLoaderRoute: typeof PProgramIdTeamTasksRouteImport
      parentRoute: typeof PProgramIdRouteRoute
    }
    '/p/$programId/stakeholders': {
      id: '/p/$programId/stakeholders'
      path: '/stakeholders'
      fullPath: '/p/$programId/stakeholders'
      preLoaderRoute: typeof PProgramIdStakeholdersRouteImport
      parentRoute: typeof PProgramIdRouteRoute
    }
    '/p/$programId/sprint-board': {
      id: '/p/$programId/sprint-board'
      path: '/sprint-board'
      fullPath: '/p/$programId/sprint-board'
      preLoaderRoute: typeof PProgramIdSprintBoardRouteImport
      parentRoute: typeof PProgramIdRouteRoute
    }
    '/p/$programId/risks': {
      id: '/p/$programId/risks'
      path: '/risks'
      fullPath: '/p/$programId/risks'
      preLoaderRoute: typeof PProgramIdRisksRouteImport
      parentRoute: typeof PProgramIdRouteRoute
    }
    '/p/$programId/program-overview': {
      id: '/p/$programId/program-overview'
      path: '/program-overview'
      fullPath: '/p/$programId/program-overview'
      preLoaderRoute: typeof PProgramIdProgramOverviewRouteImport
      parentRoute: typeof PProgramIdRouteRoute
    }
    '/p/$programId/lifecycle': {
      id: '/p/$programId/lifecycle'
      path: '/lifecycle'
      fullPath: '/p/$programId/lifecycle'
      preLoaderRoute: typeof PProgramIdLifecycleRouteImport
      parentRoute: typeof PProgramIdRouteRoute
    }
    '/p/$programId/follow-ups': {
      id: '/p/$programId/follow-ups'
      path: '/follow-ups'
      fullPath: '/p/$programId/follow-ups'
      preLoaderRoute: typeof PProgramIdFollowUpsRouteImport
      parentRoute: typeof PProgramIdRouteRoute
    }
    '/p/$programId/dependencies': {
      id: '/p/$programId/dependencies'
      path: '/dependencies'
      fullPath: '/p/$programId/dependencies'
      preLoaderRoute: typeof PProgramIdDependenciesRouteImport
      parentRoute: typeof PProgramIdRouteRoute
    }
    '/p/$programId/customer-health': {
      id: '/p/$programId/customer-health'
      path: '/customer-health'
      fullPath: '/p/$programId/customer-health'
      preLoaderRoute: typeof PProgramIdCustomerHealthRouteImport
      parentRoute: typeof PProgramIdRouteRoute
    }
    '/p/$programId/artifacts': {
      id: '/p/$programId/artifacts'
      path: '/artifacts'
      fullPath: '/p/$programId/artifacts'
      preLoaderRoute: typeof PProgramIdArtifactsRouteImport
      parentRoute: typeof PProgramIdRouteRoute
    }
    '/p/$programId/activity': {
      id: '/p/$programId/activity'
      path: '/activity'
      fullPath: '/p/$programId/activity'
      preLoaderRoute: typeof PProgramIdActivityRouteImport
      parentRoute: typeof PProgramIdRouteRoute
    }
  }
}

interface PProgramIdRouteRouteChildren {
  PProgramIdActivityRoute: typeof PProgramIdActivityRoute
  PProgramIdArtifactsRoute: typeof PProgramIdArtifactsRoute
  PProgramIdCustomerHealthRoute: typeof PProgramIdCustomerHealthRoute
  PProgramIdDependenciesRoute: typeof PProgramIdDependenciesRoute
  PProgramIdFollowUpsRoute: typeof PProgramIdFollowUpsRoute
  PProgramIdLifecycleRoute: typeof PProgramIdLifecycleRoute
  PProgramIdProgramOverviewRoute: typeof PProgramIdProgramOverviewRoute
  PProgramIdRisksRoute: typeof PProgramIdRisksRoute
  PProgramIdSprintBoardRoute: typeof PProgramIdSprintBoardRoute
  PProgramIdStakeholdersRoute: typeof PProgramIdStakeholdersRoute
  PProgramIdTeamTasksRoute: typeof PProgramIdTeamTasksRoute
  PProgramIdIndexRoute: typeof PProgramIdIndexRoute
}

const PProgramIdRouteRouteChildren: PProgramIdRouteRouteChildren = {
  PProgramIdActivityRoute: PProgramIdActivityRoute,
  PProgramIdArtifactsRoute: PProgramIdArtifactsRoute,
  PProgramIdCustomerHealthRoute: PProgramIdCustomerHealthRoute,
  PProgramIdDependenciesRoute: PProgramIdDependenciesRoute,
  PProgramIdFollowUpsRoute: PProgramIdFollowUpsRoute,
  PProgramIdLifecycleRoute: PProgramIdLifecycleRoute,
  PProgramIdProgramOverviewRoute: PProgramIdProgramOverviewRoute,
  PProgramIdRisksRoute: PProgramIdRisksRoute,
  PProgramIdSprintBoardRoute: PProgramIdSprintBoardRoute,
  PProgramIdStakeholdersRoute: PProgramIdStakeholdersRoute,
  PProgramIdTeamTasksRoute: PProgramIdTeamTasksRoute,
  PProgramIdIndexRoute: PProgramIdIndexRoute,
}

const PProgramIdRouteRouteWithChildren = PProgramIdRouteRoute._addFileChildren(
  PProgramIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PProgramIdRouteRoute: PProgramIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
